repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - "--profile"
          - "black"
          - "--line-length=88"
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args:
          - "--line-length=88"
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
          - "--extend-ignore=E203,W503"
