options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: "rank-ops"
  _REGION: "us-central1"
  _REPO: "rank-ops-repo"

steps:
- name: "gcr.io/cloud-builders/docker"
  args:
    [
      "build",
      "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/rank-ops:$BUILD_ID",
      "--platform=linux/amd64",
      "--build-arg",
      "RUN_SMOKE=1",
      "."
    ]

- name: "gcr.io/cloud-builders/docker"
  args:
    [
      "push",
      "us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/rank-ops:$BUILD_ID"
    ]

- name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
  entrypoint: gcloud
  args:
    [
      "run","deploy","$_SERVICE",
      "--image","us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/rank-ops:$BUILD_ID",
      "--region","$_REGION",
      "--platform","managed",
      "--allow-unauthenticated",
      "--port","8080",
      "--update-secrets","API_KEY=projects/$PROJECT_NUMBER/secrets/API_KEY:latest"
    ]
